name: client
description: "Flutter project my-salary app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1

  get_it: ^7.6.0
  injectable: ^2.3.2
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.2.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.6
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/countries.json
    - assets/languages.json
    - assets/religions.json
    - assets/statics.json
    - assets/workTypes.json
