server:
  port: 8080

spring:
  application:
    name: my-salary
  datasource:
    url: jdbc:postgresql://localhost:5432/my-salary
    username: my-salary
    password: my-salary
    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always